# 工作流名称
name: Guo-Habor
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Guo Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）    
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos 
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Allow Insecure Registries
      run: |
        echo '{ "insecure-registries": ["http://x454262h22.qicp.vip:86"] }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: x454262h22.qicp.vip:86
        username: ${{ secrets.NAME }}
        password: ${{ secrets.PASSWORD }}
        logout: false
        
    - name: Use Skopeo to Guo Image to Insecure Harbor Registry
      run: |
        #!/usr/bin/env bash
        skopeo copy --dest-tls-verify=false docker://docker.io/rancher/mirrored-prometheus-operator-prometheus-config-reloader:v0.59.1 docker://x454262h22.qicp.vip:86/rancher/mirrored-prometheus-operator-prometheus-config-reloader:v0.59.1




